sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-034
env:
  global:
    -
      # LTD_AWS_ID
      secure: jPw3rPgbz3mfs/4j85rzv39/oNJEWQEcI9autpOc3g7AzyeXSrPARRpPE8El8araZGlqCYrUl3bS6e5GeSt2cZhUYpA3e0D8NF/07ZO6sjEHBijnXc3CJrSMa2wDy7f0un11V/qf5GfVWKkqLHvRBkfN6LXP0BytPVayCNd6YPnb9MtExRqjWOZu/oOJBwtvvs2gTuhu4UgN3AdSZJuNV+A4Kfc9xtZ1y8WpmouTeQQgYPWIbHtoyRYh6UEP0hSeS7nnF0nfp0bi7B4rNCC40cRo4S0FJnvlki+pCmtSs7Dx9a2ZsFYXs0Z3m/nA3DDzUw8Fn1iqYw439GcBeC9OPn4PtrzN2xIuwYnwsheDKi4gvMuAtg9Zp6iCSQvL1VMExpK4YKWWBqcjejpZY0DicX+wFVBc+/IizK0yR6t3UKw+rU3r/t2OwMDr/g9mHcvTIDIe3brB7UV9DQ7WfW/rALsk/7L+kKvUdbinWXjfkUYW8Xb1WZXfvqfssumZ6viHShAnLpOZf6m3+SvpIlCqsEoy6MaEinBsSWT1Wc6bRQIYprXjM1+s5YCXCm/kRGueYsqHNWwXz0yAMScRPmcqK4IhrLFIaqbsSaNJV0tvzKpq1Taho34k9DSpTWCqyAYKvfMCsC289aDg0jjIqB5xRaq+/qq0wpT2Tj6uDE+QXuk=
    -
      # LTD_AWS_SECRET
      secure: aWUFZ5rE6E6LmxC9R45Nb+AecpBWB+DHkeFLgJeOnGK5CCyfship+G48fqewIEwjYIRkCG3gAqOzaroIyZQEY9DH7bSoAfWYDuvWMRaYRI3PR2Su2+Ru8YFxtOVldNB8qwzgLkctGjmagQbiCTS+6vuDHrkYTMSNkxBv7Snl5S7EUWPUclHsyUB+CQ2kK9J3A6h5+XNnoEDzs8wTwizHRyieGFJ6KZ4tjs4mJsCvn7dUQidbEqaRV6jFB0lDiNf7IAcpSo02+yhVTJ1DLfLMeVzt+MON7ns/SbUDjjb2zN8CX0Gb60HEHR2O7XGlvugMT7ZARNJAb9pW8NOCfiLH4lUN6pwN90xTzGsm9qqD45ToI57GUlU2B2QE0IxJab3OT4vq3YcU1XgOEEA5HdhdN0X9MtXK6QfqpSK/aVyNlw+EMMOtnPOnOxofunSpDCkVUhiPhDlIMT2sZRyNrsN+PzLeNT7HY/bO5gwg4D5O0gLEdZ6kZ/6HzZi/nJ/bSssmin7QWZ26cmxIeXDZ6iL04mZb6i+fQK98dde5skyz1YZ4N6b1P8f+k0VFC93GYg5dkS+4+5Ft7EpyDee2T1VtoO3Hg04d8QIJyj8YJioH9Xfz8PEQK3DzbJi2qJHEwvF5BJm+mh0Bpc00PDuFcC00vpdZqRj0ZcpsU/oNfWSDfXs=
    -
      # LTD_USERNAME
      secure: U6Ru2HxE+K+t5x58W+QHoQxyRwiWTe24VUCDNsr9sZz3vCntCFbzAPGolCKw+Sq7S8TRDLHpCMHC77a5mzJLPOQHTTRRwjOu5i86T+ZUbY6O4opB928DDz7fVttgRuOrF+ruvJuio6nUSTgFCtRFROjFoZwq/8s1lOCm9K/X8uxpbilb6fo6dl4LS/EpK725fJd6skpL1TmNZ6LuNEmRRYg08a+xKO2vlB87Yf0mVmiOODqUR5tMeinoKJ7+JLGHBQborx4acrV0UDjBIMV3fjWwAueB4Kwj97TASVRoNujHeQ/eFsga9CnRj6YfEqKmKjMtS4S0NtGrodJlAzUyGEaBmvTP644of2I9Yd1sKPJ9vlOSziri0rn/dbx9Db/wf3QtCNdK1JrIskht4RLkWp8y+XB9nyvvVGgWFSG/5U5YUZlmZlcSP8SkyhJINOjCA0QD08YZaWQVlpERYTJxgp0h8fq79B0zcp5F22nVqJbL+iUjqAG5Nebeyz13Cex9h+zRfZ+nQ0nY69BEHl1jD/WdRdDhkpZoAECpVGwNunw50JWhks+wRyqexe8dU/ZQ4j97317FzNUWja9/f5O4O9ddUq9jqnlpMHOWOGr0I4tgf4MKcRNwN1ZUdvx8z0EdVNEVJ2W7ZDEhwQHcO5Mmh0ew0yAGy+4DxkoSP9UwAh4=
    -
      # LTD_PASSWORD
      secure: bYTQt5zG6LfRn4xjWUfr6rHyZ7sUMzc7FypzD06cmRCA/6APAERoiTSxSiisiUzACBartD7rEPM75Pr65W6assMhGArygK0H4JsuNVoNhYdajQewh78BFpAGJQivIbwmHGS/Yfp5qb+QIGvR7oVZXK0emrOkw84LbnzxbsOLJ3tLITaXXgkpxzKK9FWg4qIFBSkXnZbVMf/gthCoER5vKytEQgELKJvkOgBD39KyN5gs1G67e+bCZySswx48/V2xoKHIDPVLwkCfC/SCTztvejHxNHLgBJ+z1DztnmNpN2qsiF1OvIZWEbakV77TYJOL8/ba3Ff1SBcLK1/cFL+HM+C+EwWpAOmH85vRwB/zrZdu0jBkSRejOZGR8Odg++J7NTpA1WhIWMKg9ekMGdvVYd/9ZFqFRE7ZA9QsekI9SFqMZHONfeoq2shqoh5Qsr+3I1nOVVn4ekmXUHoK0v7ypk9G/ebPMZ+kxJTLgQc0XE8iPCrY3YO9ROgLLZpvcsvvXAQBM4wLBmrKsIZml03oMcYWIJO5Qpda21ildVWxrK7/4kzU6S2fWzJfGXi1FzynmX5CQLazqIywMHn8PgCmwAJb1KzuspZhdRpH4Z9DNZObHys2RZQFDuin574MyLAkOjnZhCCqDrJY8ufzMkclnryXoreHIoOVARjBooae/8o=
